version: '3.7'

services:
  celery:
    build: ./pa
    command: celery -A pa worker -l info
    env_file:
      .env.dev
    volumes:
      - ./pa:/usr/src/app/
    depends_on:
      - db
      - redis
  celery-beat:
    build: ./pa
    command: celery -A pa beat -l info
    env_file:
      .env.dev
    volumes:
      - ./pa:/usr/src/app/
    depends_on:
      - redis
  django:
    build: ./pa
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pa:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.1-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      .env.dev
    ports:
      - 5432:5432
  flower:
    image: mher/flower
    command: flower --broker=redis://redis:6379/0 --port=8888
    ports:
      - 8888:8888
    depends_on:
      - celery
  redis:
    image: 'redis:alpine'

volumes:
  postgres_data:
  pa:
