version: '3'

services:

  db:
    image: postgres:latest
    env_file:
      .db_env
  backend:
    build:
      .
    command:
      python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./pa:/pa
    env_file:
      - .backend_env
    ports:
    - "8000:8000"
    depends_on:
      - db