version: '3.7'

services:
  web:
    build:
      context: ./pa
      dockerfile: Dockerfile.prod
    command: daphne -b 0.0.0.0 -p 8000 pa.asgi:application
    volumes:
      - static_volume:/home/app/pa/static
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:12.1-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/pa/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
